version: '3.8'

x-default: &x-default
  logging:
    driver: "json-file"
    options:
      max-file: 1
      max-size: 4m
  restart: always

services:
  postgres:
    <<: *x-default
    image: postgres:15.3-alpine
    networks:
      - workspace
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_root_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_name
      - db_root_username
      - db_root_password

  postgres-backup:
    <<: *x-default
    image: prodrigestivill/postgres-backup-local:15-alpine-8d72d2d
    networks:
      - workspace
    volumes:
      - postgres_backup:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_root_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    secrets:
      - db_name
      - db_root_username
      - db_root_password

secrets:
  db_name:
    file: db_name.txt
  db_root_username:
    file: db_root_username.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  postgres_data:
  postgres_backup:
