version: '3.8'

x-default: &x-default
  logging:
    driver: "json-file"
    options:
      max-file: 1
      max-size: 4m
  restart: always

services:
  postgres:
    <<: *x-default
    image: postgres:15.3-alpine
    networks:
      - workspace
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_POSTGRES_DB}

  postgres-backup:
    <<: *x-default
    image: prodrigestivill/postgres-backup-local:15-alpine-8d72d2d
    networks:
      - workspace
    volumes:
      - postgres_backup:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  postgres_data:
  postgres_backup:
